name: cmsd_home
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  icons_plus: ^4.0.0
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^5.0.2
  get: ^4.6.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  google_sign_in: ^6.2.1
  google_sign_in_web: ^0.12.3+1
  flutter_spinkit: ^5.1.0
  flutter_bluetooth_seria_changed: ^0.4.0
  firebase_database: ^10.3.8
  open_settings: ^2.0.2
  permission_handler: ^11.1.0
  percent_indicator: ^4.2.3
  lottie: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/facebook.png
    - assets/google.png
    - assets/images/apple.png
    - assets/images/CMSD.png
    - assets/images/profile.png
    - assets/images/notcon.png
