// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlnEZxfv-i2Q3Z5JyURl0Pe04hfC8A7qI',
    appId: '1:191251944607:web:07c802301fc4f880583eaa',
    messagingSenderId: '191251944607',
    projectId: 'cmsd-1b8c4',
    authDomain: 'cmsd-1b8c4.firebaseapp.com',
    storageBucket: 'cmsd-1b8c4.appspot.com',
    measurementId: 'G-K1K8C29RB4',
    databaseURL:
        'https://cmsd-1b8c4-default-rtdb.europe-west1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3HQEGVC4PSuHI34qscVQxOEwXQ_FYGSA',
    appId: '1:191251944607:android:7eada5fb1886db13583eaa',
    messagingSenderId: '191251944607',
    projectId: 'cmsd-1b8c4',
    storageBucket: 'cmsd-1b8c4.appspot.com',
    databaseURL:
        'https://cmsd-1b8c4-default-rtdb.europe-west1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaNuF4wwWlklRUfvwA18tSV9MYnaDnVQM',
    appId: '1:191251944607:ios:eecfaa4a7b21af59583eaa',
    messagingSenderId: '191251944607',
    projectId: 'cmsd-1b8c4',
    storageBucket: 'cmsd-1b8c4.appspot.com',
    iosBundleId: 'com.example.cmsdHome',
    databaseURL:
        'https://cmsd-1b8c4-default-rtdb.europe-west1.firebasedatabase.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaNuF4wwWlklRUfvwA18tSV9MYnaDnVQM',
    appId: '1:191251944607:ios:69ef5e560484d092583eaa',
    messagingSenderId: '191251944607',
    projectId: 'cmsd-1b8c4',
    storageBucket: 'cmsd-1b8c4.appspot.com',
    iosBundleId: 'com.example.cmsdHome.RunnerTests',
    databaseURL:
        'https://cmsd-1b8c4-default-rtdb.europe-west1.firebasedatabase.app',
  );
}
